### ISSUE TITLE
Share episode URL with timecode

### ISSUE THREAD

**Issue by haslinger** [podigee/podigee-podcast-player#24]
I would like to reopen #5 ;-)

It drove me nuts to see, that this works with your demo, but it _'didn't work for me'_. So I dug into this and found out, that it works with the player hosted on github:
https://podigee.github.io/podigee-podcast-player/build/javascripts/podigee-podcast-player.js
but it doesn't work with the one mentioned in the docs: 
https://cdn.podigee.com/podcast-player/javascripts/podigee-podcast-player.js

Maybe it's still an older version there? 
Merry Christmas from Vienna and congrats for your great player :1st_place_medal:

**Comment by haslinger** [comment]
Well .. it's 🎅 ... time for wishes ... it would be 😍 to share a snippet ... like #t=777&d=28 ... in the sense of 28 seconds starting from second 777 ...

**Comment by benzimmer** [comment]
The bug preventing the deeplink to work is fixed now and I also took the chance to fully implement the solution described here: https://podlove.org/deep-link/

So URLs like this should work as expected:

```
https://example.com/ep-1/#t=123          # plays from second 123 to the end
https://example.com/ep-1/#t=,123         # plays from start to second 123
https://example.com/ep-1/#t=123,321   # plays from second 123 to second 321
https://example.com/ep-1/#t=00:01:00 # plays from minute 1 to the end 321
...
```

**Comment by haslinger** [comment]
I believe, we see a regression here: 
`http://podigee.github.io/podigee-podcast-player/#t=10,20`
throws a
```
Uncaught TypeError: Failed to set the 'currentTime' property on 'HTMLMediaElement': The provided double value is non-finite.
    at t.setInitialTime (http://podigee.github.io/podigee-podcast-player/build/javascripts/podigee-podcast-player.js:8:21895)
    at t.setInitialTime (http://podigee.github.io/podigee-podcast-player/build/javascripts/podigee-podcast-player.js:8:19751)
    at new t (http://podigee.github.io/podigee-podcast-player/build/javascripts/podigee-podcast-player.js:8:20432)
    at t.initPlayer (http://podigee.github.io/podigee-podcast-player/build/javascripts/podigee-podcast-player.js:7:22865)
    at t.initPlayer (http://podigee.github.io/podigee-podcast-player/build/javascripts/podigee-podcast-player.js:7:20941)
    at Object.<anonymous> (http://podigee.github.io/podigee-podcast-player/build/javascripts/podigee-podcast-player.js:7:22116)
    at c (http://podigee.github.io/podigee-podcast-player/build/javascripts/podigee-podcast-player.js:2:6371)
    at Object.fireWith [as resolveWith] (http://podigee.github.io/podigee-podcast-player/build/javascripts/podigee-podcast-player.js:2:7188)
    at Object.i.(anonymous function) [as resolve] (http://podigee.github.io/podigee-podcast-player/build/javascripts/podigee-podcast-player.js:2:8178)
    at Object.<anonymous> (http://podigee.github.io/podigee-podcast-player/build/javascripts/podigee-podcast-player.js:7:22757)
t.setInitialTime @ podigee-podcast-player.js:8
(anonymous) @ podigee-podcast-player.js:8
t @ podigee-podcast-player.js:8
t.initPlayer @ podigee-podcast-player.js:7
(anonymous) @ podigee-podcast-player.js:7
(anonymous) @ podigee-podcast-player.js:7
c @ podigee-podcast-player.js:2
fireWith @ podigee-podcast-player.js:2
i.(anonymous function) @ podigee-podcast-player.js:2
(anonymous) @ podigee-podcast-player.js:7
c @ podigee-podcast-player.js:2
fireWith @ podigee-podcast-player.js:2
i.(anonymous function) @ podigee-podcast-player.js:2
(anonymous) @ podigee-podcast-player.js:8
c @ podigee-podcast-player.js:2
fireWith @ podigee-podcast-player.js:2
n @ podigee-podcast-player.js:3
e @ podigee-podcast-player.js:3
podigee-podcast-player.js:7 Uncaught TypeError: Cannot read property 'updateBarWidths' of undefined
    at t.sendSizeChange (podigee-podcast-player.js:7)
    at t.sendSizeChange (podigee-podcast-player.js:7)
    at HTMLImageElement.<anonymous> (podigee-podcast-player.js:8)
    at HTMLImageElement.dispatch (podigee-podcast-player.js:2)
    at HTMLImageElement.m.handle (podigee-podcast-player.js:2)
```
